---
title: "ELF Multivariate Analysis"
output: word_document
---
```{r include = FALSE, warning = FALSE}
library(quantreg);
library(knitr)
# install.packages('pander')
library(pander)

fe_data <- function (
  bundle = 'watershed', 
  ftype = 'ecoregion_iii',
  metric = 'aqbio_nt_benins',
  selected = 'all',
  quantile = 0.8,
  DA.thresh = 500,
  site = 'd.dh') {
  # load data for select ecoregion
  uri <- paste("http://deq1.bse.vt.edu", site, "multivariate/max", metric, bundle, ftype, selected, sep='/') 
  print(paste('uri: ', uri, sep = '')) 
  data <- read.csv(uri, header = TRUE, sep = ",")
  #makes sure all metric values are numeric and not factorial (fixes error with ni, total)
  data$metric_value <- as.numeric(data$metric_value)
  return(data )
}
```

This is a comparison of linear models for ecology = f(log(DA)), ecology = f(log(DA), log(Qmean)), and ecology = f(log(DA), log(Qmonths stepwise)).

```{r include = FALSE, warning = FALSE}
bundle <- 'watershed'; # ecoregion, watershed, landunit
ftype <- 'nhd_huc8'; # state, hwi_region, nhd_huc8, nhd_huc6, ecoregion_iii, ecoregion_iv, ecoiii_huc6
metric <- 'aqbio_nt_cent';
selected <- 'nhd_huc8_06010205';
quantile <- 0.8;
# breakpoint for DA/Q (~ 500 cfs?)
DA.thresh <- 2852;
site <- 'd.dh';
exc <- TRUE; # exclude stations with DA > 1000 * mean annual flow
```

* Location: `r selected`
* quantile: `r quantile`
* Metric: `r metric`
* Exclude Sites With DA > 1,000*Q: `r exc`

```{r include = FALSE, warning = FALSE}
data <- fe_data(bundle, ftype, metric, selected, quantile, DA.thresh, site);
if (exc) {
  dme <- subset(data, da_sqkm >= .001 & da_sqkm < DA.thresh & da_sqkm < (1000 * annual));
} else {
  dme <- subset(data, da_sqkm >= .001 & da_sqkm < DA.thresh);
}
#calculate the quantile regression
up90 <- rq(metric_value ~ log(annual),data = dme, tau = quantile)
#find the values of upper quantile values of y for each value of DA based on the quantile regression
newy <- c(log(dme$annual)*coef(up90)[2]+coef(up90)[1])
#create a subset of the data that only includes the stations with NT values higher than the y values just calculated
upper.quant <- subset(dme, dme$metric_value > newy)
fit1 <- lm(metric_value ~ log(da_sqkm), data = upper.quant)
summary(fit1);

fit2 <- lm(metric_value ~ log(da_sqkm) + log(annual), data = upper.quant)
summary(fit2);

fit_annual <- lm(metric_value ~ log(annual), data = upper.quant)
summary(fit_annual);

fit_jan <- lm(metric_value ~ log(jan), data = upper.quant)
summary(fit_jan);

fit_feb <- lm(metric_value ~ log(feb), data = upper.quant)
summary(fit_feb);

fit_mar <- lm(metric_value ~ log(mar), data = upper.quant)
summary(fit_mar);

fit_apr<- lm(metric_value ~ log(apr), data = upper.quant)
summary(fit_apr);

fit_may <- lm(metric_value ~ log(may), data = upper.quant)
summary(fit_may);

fit_jun <- lm(metric_value ~ log(jun), data = upper.quant)
summary(fit_jun);

fit_jul <- lm(metric_value ~ log(jul), data = upper.quant)
summary(fit_jul);

fit_aug <- lm(metric_value ~ log(aug), data = upper.quant)
summary(fit_aug);

fit_sep <- lm(metric_value ~ log(sep), data = upper.quant)
summary(fit_sep);

fit_oct <- lm(metric_value ~ log(oct), data = upper.quant)
summary(fit_oct);

fit_nov <- lm(metric_value ~ log(nov), data = upper.quant)
summary(fit_nov);

fit_dec <- lm(metric_value ~ log(dec), data = upper.quant)
summary(fit_dec);


library(MASS)
fit <- lm(metric_value ~ log(da_sqkm) + log(jan) + log(feb) + 
            log(mar) + log(apr) + log(may)
          + log(jun) + log(jul) + log(aug) 
          + log(sep) + log(oct) + log(nov) + log(dec)
          ,data=upper.quant
)
step <- stepAIC(fit, direction="both")
```

```{r }
step$anova # display results

# kable and pander are both ways to show tables in RMarkdown
# pander handles the lm() summary object, but kable can only handle excerpts of it 
# or the output of anova, so I use pander here
#kable(anova(fit1), digits=2);
pander(summary(fit1), digits=2);
plot(upper.quant$metric_value, fitted(fit1), ylab=fit1$call[2])
pander(summary(fit2), digits=2);
plot(upper.quant$metric_value, fitted(fit2))
pander(summary(fit_annual), digits=2);
plot(upper.quant$metric_value, fitted(fit_annual), ylab=fit2$call[2])
#kable(anova(step), digits=2);
pander(summary(step), digits=2);
plot(upper.quant$metric_value, fitted(step), ylab=step$call[2])
pander(summary(step), digits=2);

mofit = list(fit_jan, fit_feb, fit_mar, fit_apr, fit_may, fit_jun, fit_jul, fit_aug, fit_sep, fit_oct, fit_nov, fit_dec)
for (moreg in mofit) {
  pander(summary(moreg), digits=2);
  plot(upper.quant$metric_value, fitted(moreg), ylab = moreg$call[2])
}

# GIVES GOOD SCREEN POUTPUT WITH P AND r2 BUT CRUDDY wORD OUTPUT
# install.packages('sjPlot')
#library(sjPlot)
#sjt.lm(fit1,fit2,step, file="output.html")# You have to save the table in html format.
#htmltools::includeHTML("output.html")# Finally you can call it from markdown

```





