---
title: "ELF Monthly Comparisons"
output: word_document
---

```{r, echo=FALSE}
# install.packages('gdata')
library('gdata')
fxn_locations = '/usr/local/home/git/r-dh-ecohydro/Analysis';
source(paste(fxn_locations,"query_elf_statistics.R", sep = "/")); 

bundle <- 'watershed';
ftype <- 'nhd_huc6';
metric <- 'aqbio_nt_cypr_native';
q_ftype <- "fe_quantreg";
analysis_timespan = "full";
sampres = "species";
selected <- 'all'; # all or hydrocode
quantile <- 0.9;
stat_quantreg_glo <- 0; # use 1 for pwit, 0 for quantreg
# ftype = fe_quantreg, fe_quantreg_pwit, fe_quantreg_ymax, fe_twopoint
# analysis_timespan = full, 1990-2010, 1970-1980, ...
data = fn_dh_elfstats (
    ftype = q_ftype,
    analysis_timespan = analysis_timespan,
    yvar = metric,
    sampres = sampres,
    stat_quantreg_qu = quantile,
    feature_ftype = ftype,
    stat_quantreg_glo = 0
);
data <- subset(data, !is.na(out_rsq));
data.da <- subset(data, in_xvar == 'nhdp_drainage_sqkm') ;
data.mean <- subset(data, in_xvar == 'erom_q0001e_mean');
data.jan <- subset(data, in_xvar == 'erom_q0001e_jan');
data.feb <- subset(data, in_xvar == 'erom_q0001e_feb');
data.mar <- subset(data, in_xvar == 'erom_q0001e_mar');
data.apr <- subset(data, in_xvar == 'erom_q0001e_apr');
data.may <- subset(data, in_xvar == 'erom_q0001e_may');
data.jun <- subset(data, in_xvar == 'erom_q0001e_june');
data.jul <- subset(data, in_xvar == 'erom_q0001e_july');
data.aug <- subset(data, in_xvar == 'erom_q0001e_aug');
data.sep <- subset(data, in_xvar == 'erom_q0001e_sept');
data.oct <- subset(data, in_xvar == 'erom_q0001e_oct');
data.nov <- subset(data, in_xvar == 'erom_q0001e_nov');
data.dec <- subset(data, in_xvar == 'erom_q0001e_dec');
n = c('DA', 'Mean', 'January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December')
title <- paste("R^2 of upper ", 100.*(1.0 - quantile), "% for \n", metric, " = f(DA), f(Qmean), f(Qjan),..., f(Qdec) for ", ftype);
if (length(data.da$s_adminid) > 1) {
  boxplot(
    data.da$out_rsq_adj, data.mean$out_rsq_adj, data.jan$out_rsq_adj, data.feb$out_rsq_adj, data.mar$out_rsq_adj, 
      data.apr$out_rsq_adj, data.may$out_rsq_adj, data.jun$out_rsq_adj, data.jul$out_rsq_adj, data.aug$out_rsq_adj, 
      data.sep$out_rsq_adj, data.oct$out_rsq_adj, data.nov$out_rsq_adj, data.dec$out_rsq_adj,
    names = n, 
    main = title
  );
} else {
  # we are running a single watershed, so use a bar chart
  nms = strsplit(as.vector(data$in_xvar), '_', fixed = TRUE);
  xs = matrix(unlist(nms),ncol=3,byrow=TRUE)
  labs = xs[,3]
  par(las=1) # make label text perpendicular to axis
  barplot(data$out_rsq_adj, names.arg=labs, main=paste("R# for region", selected), 
          xlab="DA/Flow Variable")
  
}
```
* Location: `r selected`
* quantile: `r quantile`
* Metric: `r metric`
* Geospatial Unit: `r ftype`
* Analysis Type: `r q_ftype`
* Timespan: `r analysis_timespan`
```{r, echo=FALSE,fig.width=3, fig.show='hold'}
cs = c( 'sqkm', 'mean', 'jan', 'feb', 'mar', 'apr', 'may', 'june', 'july', 'aug', 'sept', 'oct', 'nov', 'dec');
# coloring bar plots: https://stackoverflow.com/questions/16121903/r-barplot-y-axis-scale-too-short
  for (i in 1:nrow(data.da)) {
  hc = data.da$containing_hydrocode[i]
  data.hc = subset(data, containing_hydrocode == hc)
  data.sorted = c(
    subset(data.hc, in_xvar == 'nhdp_drainage_sqkm')$out_rsq_adj,
    subset(data.hc, in_xvar == 'erom_q0001e_mean')$out_rsq_adj,
    subset(data.hc, in_xvar == 'erom_q0001e_jan')$out_rsq_adj,
    subset(data.hc, in_xvar == 'erom_q0001e_feb')$out_rsq_adj,
    subset(data.hc, in_xvar == 'erom_q0001e_mar')$out_rsq_adj,
    subset(data.hc, in_xvar == 'erom_q0001e_apr')$out_rsq_adj,
    subset(data.hc, in_xvar == 'erom_q0001e_may')$out_rsq_adj,
    subset(data.hc, in_xvar == 'erom_q0001e_jun')$out_rsq_adj,
    subset(data.hc, in_xvar == 'erom_q0001e_jul')$out_rsq_adj,
    subset(data.hc, in_xvar == 'erom_q0001e_aug')$out_rsq_adj,
    subset(data.hc, in_xvar == 'erom_q0001e_sep')$out_rsq_adj,
    subset(data.hc, in_xvar == 'erom_q0001e_oct')$out_rsq_adj,
    subset(data.hc, in_xvar == 'erom_q0001e_nov')$out_rsq_adj,
    subset(data.hc, in_xvar == 'erom_q0001e_dec')$out_rsq_adj
  )
  # try to create formatted names from variable abbreviations
  nms = strsplit(as.vector(data.hc$in_xvar), '_', fixed = TRUE);
  xs = matrix(unlist(nms),ncol=3,byrow=TRUE);
  labs = xs[,3]
  labs = subset(labs[match(cs,labs)], labs[match(cs,labs)] != 'NA')
  par(las=2) # make label text perpendicular to axis
  barplot(data.hc$out_rsq_adj, names.arg=labs, main=paste("R# ", hc), 
          xlab="DA/Flow Variable", ylim=c(0,1.0))
}
```